# Problem 1 - Sorting

1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.

In [ ]:
import pandas as pd

titanic_df = pd.read_csv('/content/drive/MyDrive/Datasets/Week2/Titanic-Dataset.csv')
display(titanic_df.head())

print()
#DataFrame called fare that contains onl the Fare column

fare_df = titanic_df['Fare']
fare_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.

In [ ]:
class_age = titanic_df[['Pclass','Age']]
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [ ]:
survived_gender = titanic_df[['Survived','Sex']]
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

# Problem 2 - Subsetting

1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.

In [ ]:
fare_gt_100 = titanic_df.loc[titanic_df['Fare']>100]
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.

In [ ]:
first_class = titanic_df.loc[titanic_df['Pclass']==1]
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [ ]:
female_under_18 = titanic_df.loc[(titanic_df['Sex']== 'female') & (titanic_df['Age']<18)]
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

## Subsetting Rows by Categorical Variables

1. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [ ]:
embarked_c_or_s = titanic_df.loc[(titanic_df['Embarked']=='C') | (titanic_df['Embarked']=='S') ]
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first_second_class.View the printed result.

In [ ]:
first_second_class = titanic_df.loc[(titanic_df['Pclass']==1)| (titanic_df['Pclass']==2)]
first_second_class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

# Exploratory Data Analysis Practice Exercise-1

## Which passenger had the highest fare paid relative to their age?

1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).

In [ ]:
import pandas as pd

titanic_df = pd.read_csv('/content/drive/MyDrive/Datasets/Week2/Titanic-Dataset.csv')

#Filling the empty values of age with the mean to aid in division
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())

titanic_df['fare_per_year'] = titanic_df['Fare']/titanic_df['Age']
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000

2. Subset rows where fare_per_year is higher than 5, assigning this to high_fare_age.

In [ ]:
high_fare_age = titanic_df.loc[titanic_df['fare_per_year']>5]
high_fare_age.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,5.669643

3. Sort high_fare_age by descending fare per year, assigning this to high fare age srt.

In [ ]:
high_fare_age_srt = high_fare_age.sort_values(by='fare_per_year', ascending = False)
display(high_fare_age_srt.head())
print()
print("Tail")
print()

high_fare_age_srt.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,39.000000

Tail

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S,5.318281
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.0,1,1,C.A. 37671,15.9000,NaN,S,5.300000
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S,5.231250
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S,5.212500
480,481,0,3,"Goodwin, Master. Harold Victor",male,9.0,5,2,CA 2144,46.9000,NaN,S,5.211111

4. Select only the Name and fare_per_yearcolumns of high fare age srt and save the result as result.

In [ ]:
result = high_fare_age_srt[['Name','fare_per_year']]
result

                                       Name  fare_per_year
305          Allison, Master. Hudson Trevor     164.728261
297            Allison, Miss. Helen Loraine      75.775000
386         Goodwin, Master. Sidney Leonard      46.900000
164            Panula, Master. Eino Viljami      39.687500
183               Becker, Master. Richard F      39.000000
..                                      ...            ...
318                Wick, Miss. Mary Natalie       5.318281
348  Coutts, Master. William Loch "William"       5.300000
205              Strom, Miss. Telma Matilda       5.231250
813      Andersson, Miss. Ebba Iris Alfrida       5.212500
480          Goodwin, Master. Harold Victor       5.211111

[70 rows x 2 columns]

From the result we can observe that Passenger Allison, Master. Hudson Trevor had the highest fare paid relative to their age

## Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their class?

1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.

In [ ]:
import pandas as pd

titanic_df = pd.read_csv('/content/drive/MyDrive/Datasets/Week2/Titanic-Dataset.csv')

titanic_df['fare_per_class'] = titanic_df['Fare']/titanic_df['Pclass']

titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2.683333

2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.

In [ ]:
adult_males = titanic_df.loc[(titanic_df['Sex']=="male")&(titanic_df['Age']>=18)]
adult_males.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2.416667
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2.683333
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,51.862500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,2.683333
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,10.425000

3. Sort adult males by descending fare per class, assigning this to adult males srt.

In [ ]:
adult_males_srt = adult_males.sort_values(by="fare_per_class",ascending=False)
adult_males_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_class
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,512.3292
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,263.0000
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,263.0000
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,247.5208

4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.

In [ ]:
result = adult_males_srt[['Name','Age','fare_per_class']]
result

                                   Name   Age  fare_per_class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
438                   Fortune, Mr. Mark  64.0        263.0000
27       Fortune, Mr. Charles Alexander  19.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208
..                                  ...   ...             ...
806              Andrews, Mr. Thomas Jr  39.0          0.0000
597                 Johnson, Mr. Alfred  49.0          0.0000
263               Harrison, Mr. William  40.0          0.0000
271        Tornquist, Mr. William Henry  25.0          0.0000
822     Reuchlin, Jonkheer. John George  38.0          0.0000

[395 rows x 3 columns]

From the result, we can observe that the adult male passenger who paid hte highest fare relative to their class is Lesurer, Mr. Gustave J

# Exploratory Data Analysis with Group-by Method Practice Exercise:

## What percent of the total fare revenue came from each passenger class?

1. Calculate the total Fare paid across all passengers in the Titanic dataset.

In [ ]:
import pandas as pd

titanic_df = pd.read_csv('/content/drive/MyDrive/Datasets/Week2/Titanic-Dataset.csv')

total_fare = titanic_df['Fare'].sum()
print(total_fare)

28693.9493

2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.

In [ ]:
grouped_fares = titanic_df.groupby('Pclass')['Fare'].sum()
display(grouped_fares)
print("Proportion fare revenue by class is given below!")
proportion_fare_revenue_by_class = grouped_fares/total_fare
proportion_fare_revenue_by_class

Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64

Proportion fare revenue by class is given below!

Pclass
1    0.633493
2    0.132496
3    0.234011
Name: Fare, dtype: float64

## What percent of the total number of passengers on the Titanic belonged to each age group (e.g., child, adult, senior)?

1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18-64), and "senior" (age 65 and above).

In [10]:
# Filling the age to adjust for null values
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())

titanic_df["age_group"] = titanic_df["Age"].apply(
    lambda age: "child" if age < 18 else ("adult" if age < 65 else "senior")
)
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.00,NaN,S,adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.00,B42,S,adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.45,NaN,S,adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.00,C148,C,adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.75,NaN,Q,adult

2. Calculate the total number of passengers on the Titanic

In [4]:
no_of_passengers = len(titanic_df)
no_of_passengers

891

3. Count the number of passengers in each age group

In [17]:
age_groups = titanic_df.groupby('age_group')['Age'].count()
age_groups.head()

age_group
adult     767
child     113
senior     11
Name: Age, dtype: int64

4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.

In [18]:
age_group_proportion = age_groups/no_of_passengers
age_group_proportion

age_group
adult     0.860831
child     0.126824
senior    0.012346
Name: Age, dtype: float64

In [19]:
age_group_percentage = age_group_proportion * 100
print("The percentage of people according to age group is:")
age_group_percentage

The percentage of people according to age group is:

age_group
adult     86.083053
child     12.682379
senior     1.234568
Name: Age, dtype: float64